name: publish package

on:
   push:
      branches: ['main']
   pull_request:
      branches: ['main']
   release:
      types: [created]

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - uses: actions/setup-node@v3
           with:
              node-version: 18.7.0
         - run: npm ci --legacy-peer-deps
         - run: npm test

   publish-gpr:
      needs: build
      runs-on: ubuntu-latest
      permissions:
         packages: write
         contents: read
      steps:
         - uses: actions/checkout@v3
         - uses: actions/setup-node@v3
           with:
              node-version: 18.7.0
              registry-url: https://npm.pkg.github.com/
         - run: npm ci --legacy-peer-deps
         - run: npm publish
           env:
              NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
